import type { Metadata } from "next";
import "./globals.css";

import { DM_Sans } from "@next/font/google";
import { SidebarComponent } from "./components/Sidebar";
import Navbar from "./components/Navbar";

const dmSans = DM_Sans({
  variable: "--font-dmsans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ship Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${dmSans.variable} antialiased`}>
        <div className="flex flex-col">
          <Navbar></Navbar>
          <div className="flex items-center justify-center w-full h-screen bg-[#161716]">
            <SidebarComponent></SidebarComponent>
            {children}{" "}
          </div>
        </div>
      </body>
    </html>
  );
}
