import type { Metadata } from "next";
import "./globals.css";

import { DM_Sans } from '@next/font/google';

const dmSans = DM_Sans({
  variable:"--font-dmsans",
  weight: ['400', '500', '700'], 
  subsets: ['latin'], 
});

export const metadata: Metadata = {
  title: "Ship Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
