import type { Metadata } from "next";
import "./globals.css";

import { DM_Sans } from "@next/font/google";
import { SidebarComponent } from "./components/Sidebar";
import Navbar from "./components/Navbar";

const dmSans = DM_Sans({
  variable: "--font-dmsans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ship Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${dmSans.variable} antialiased`}>
        <div className="flex flex-col w-full ">
          <Navbar></Navbar>
          <div className="flex flex-1 min-h-screen w-full">
            <SidebarComponent />
            <main className="flex flex-1 items-center justify-center bg-[#161716] h-screen w-full">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
